
version: '3'

services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./configs/sql:/docker-entrypoint-initdb.d
    ports:
      - 9910:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  minio:
    image: "quay.io/minio/minio:RELEASE.2022-08-02T23-59-16Z"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio/data1:/data1"
      - "./minio/data2:/data2"
    command: server --console-address ":9001" http://minio/data{1...2}
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      # - MINIO_SERVER_URL=http://0.0.0.0:9000
    #- MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
    #- MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


#  Etcd:
#    image: "quay.io/coreos/etcd:v3.5.5"
#    environment:
#      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
#      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
#      - ETCDCTL_API=3
#    ports:
#      - 2379:2379
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "16686:16686"