// Code generated by hertz generator.

package main

import (
	"Simple-Douyin-Backend/messageServer"
	"Simple-Douyin-Backend/mw"
	"Simple-Douyin-Backend/service/db"
	"Simple-Douyin-Backend/service/minio"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts("0.0.0.0:8080"))
	// h.StaticFile("/main", "./static/bear.mp4")
	db.Init()
	minio.Init()
	mw.InitJwt()
	register(h)
	go messageServer.RunMessageServer()
	h.Spin()
}
