// Code generated by hertz generator.

package main

import (
	"Simple-Douyin-Backend/messageServer"
	"Simple-Douyin-Backend/mw"
	"Simple-Douyin-Backend/service/db"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts("127.0.0.1:8080"))
	db.Init()
	mw.InitJwt()
	register(h)
	go messageServer.RunMessageServer()
	h.Spin()
}
