// Code generated by hertz generator.

package handler

import (
	"Simple-Douyin-Backend/mw"
	"Simple-Douyin-Backend/service/db"
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	user, _ := c.Get(mw.IdentityKey)
	c.JSON(200, utils.H{
		"message": fmt.Sprintf("username:%#v", user.(*db.User).UserName),
	})
}
